name = "TabularFunctions"
uuid = "7add9882-6fce-4afb-882d-af036a41bc9c"
authors = ["Craig M. Hamel <cmhamel32@gmail.com>"]
version = "0.1.0"

[weakdeps]
Adapt = "79e6a3ab-5dfb-504d-930d-738a2a938a0e"

[extensions]
TabularFunctionsAdaptExt = ["Adapt"]

[compat]
Adapt = "4"
Test = "1"
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Adapt", "Test"]
